### Successful login
POST https://lab2-fuc6cchegbhrh7fa.canadacentral-01.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password123"
}

### Failed login
POST https://lab2-fuc6cchegbhrh7fa.canadacentral-01.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "wrongpassword"
}